apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamilton-backend
  namespace: hamilton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamilton-backend
  template:
    metadata:
      labels:
        app: hamilton-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["sh","-c","until nc -z hamilton-postgres 5432; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: hamilton-backend
          image: samirhasanov/hamilton_backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          startupProbe:
            tcpSocket:
              port: 8085
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://hamilton-postgres:5432/hamilton_finance"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hamilton-postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hamilton-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: HAMILTON_MINIO_ENDPOINT
              value: "http://hamilton-minio:9000"
            - name: HAMILTON_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hamilton-minio-secret
                  key: access-key
            - name: HAMILTON_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hamilton-minio-secret
                  key: secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: hamilton-backend
  namespace: hamilton
spec:
  type: ClusterIP
  selector:
    app: hamilton-backend
  ports:
    - port: 8085
      targetPort: 8085